name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
        
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: |
            chmod +x gradlew;
            ./gradlew build test javadoc shadowJar;
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Minecraft-Server
          path: server/build/libs
      - name: Upload java doc artifact
        uses: actions/upload-artifact@v3
        with:
          name: Java Documentation
          path: api/build/docs

